// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWVbYJBQ83t7uXqqjm5GYGS8MBeiiV09Y',
    appId: '1:574340220712:web:8870a5a3bb13ce44bdf21d',
    messagingSenderId: '574340220712',
    projectId: 'flutter-chat-f6813',
    authDomain: 'flutter-chat-f6813.firebaseapp.com',
    storageBucket: 'flutter-chat-f6813.appspot.com',
    measurementId: 'G-FKVWF77SJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVDnEdF5i7cEDPH38K1XrML4O7-EQR7W8',
    appId: '1:574340220712:android:6689de3d8582d5e3bdf21d',
    messagingSenderId: '574340220712',
    projectId: 'flutter-chat-f6813',
    storageBucket: 'flutter-chat-f6813.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvgS27pFGN5EqMOiFyxwTzfZQeKDBbxhw',
    appId: '1:574340220712:ios:362c84604e826cfabdf21d',
    messagingSenderId: '574340220712',
    projectId: 'flutter-chat-f6813',
    storageBucket: 'flutter-chat-f6813.appspot.com',
    iosClientId: '574340220712-o2musqqno7k743no3kpbspscdqbdclhe.apps.googleusercontent.com',
    iosBundleId: 'com.yourdomain.yourAppClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvgS27pFGN5EqMOiFyxwTzfZQeKDBbxhw',
    appId: '1:574340220712:ios:362c84604e826cfabdf21d',
    messagingSenderId: '574340220712',
    projectId: 'flutter-chat-f6813',
    storageBucket: 'flutter-chat-f6813.appspot.com',
    iosClientId: '574340220712-o2musqqno7k743no3kpbspscdqbdclhe.apps.googleusercontent.com',
    iosBundleId: 'com.yourdomain.yourAppClass',
  );
}
